# Generated by Django 4.1.1 on 2022-11-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="account_approve_queue",
            fields=[
                (
                    "OId",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="OId"
                    ),
                ),
                ("CodeName", models.CharField(max_length=30, verbose_name="CodeName")),
                ("Password", models.CharField(max_length=20, verbose_name="Password")),
                (
                    "Permission",
                    models.PositiveSmallIntegerField(verbose_name="Permission"),
                ),
                ("Class", models.CharField(max_length=20, verbose_name="Class")),
                ("Region", models.CharField(max_length=30, verbose_name="Region")),
                ("Race", models.CharField(max_length=20, verbose_name="Race")),
                ("Description", models.TextField(verbose_name="Bio")),
            ],
        ),
        migrations.CreateModel(
            name="user_account",
            fields=[
                (
                    "OId",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="OId"
                    ),
                ),
                ("CodeName", models.CharField(max_length=30, verbose_name="CodeName")),
                ("Password", models.CharField(max_length=20, verbose_name="Password")),
                ("Permission", models.IntegerField(verbose_name="Permission")),
                ("Mail", models.CharField(max_length=20, verbose_name="Mail")),
            ],
        ),
        migrations.CreateModel(
            name="user_profile",
            fields=[
                (
                    "OId",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="OId"
                    ),
                ),
                ("CodeName", models.CharField(max_length=30, verbose_name="CodeName")),
                (
                    "Gender",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "male"), (1, "female")], verbose_name="Gender"
                    ),
                ),
                ("Class", models.CharField(max_length=20, verbose_name="Class")),
                ("Region", models.CharField(max_length=30, verbose_name="Region")),
                ("Race", models.CharField(max_length=20, verbose_name="Race")),
                (
                    "Avatar",
                    models.ImageField(null=True, upload_to="", verbose_name="Avatar"),
                ),
                ("Bio", models.TextField(verbose_name="Bio")),
            ],
        ),
    ]
