# Generated by Django 4.1.1 on 2022-12-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountApproveQueue',
            fields=[
                ('CodeName', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='CodeName')),
                ('Password', models.CharField(max_length=20, verbose_name='Password')),
                ('Permission', models.IntegerField(default=3, verbose_name='Permission')),
                ('Class', models.CharField(max_length=20, verbose_name='Class')),
                ('Region', models.CharField(max_length=30, verbose_name='Region')),
                ('Race', models.CharField(max_length=20, verbose_name='Race')),
                ('Description', models.TextField(default='', verbose_name='Description')),
            ],
            options={
                'db_table': 'account_approve_queue',
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('PId', models.IntegerField(primary_key=True, serialize=False, verbose_name='PId')),
                ('Title', models.CharField(max_length=45, verbose_name='Title')),
                ('Poster', models.CharField(max_length=30, verbose_name='Poster')),
                ('PostDate', models.TimeField(max_length=20, verbose_name='PostDate')),
                ('LastEditor', models.CharField(max_length=30, verbose_name='LastEditor')),
                ('Content', models.TextField(verbose_name='Content')),
                ('Type', models.IntegerField(default=1, verbose_name='Type')),
            ],
            options={
                'db_table': 'passage',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('CodeName', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='CodeName')),
                ('Password', models.CharField(max_length=20, verbose_name='Password')),
                ('Permission', models.PositiveSmallIntegerField(verbose_name='Permission')),
                ('Mail', models.CharField(default='', max_length=20, verbose_name='Mail')),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('CodeName', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='CodeName')),
                ('Gender', models.IntegerField(choices=[(0, 'male'), (1, 'female')], verbose_name='Gender')),
                ('Class', models.CharField(max_length=20, verbose_name='Class')),
                ('Region', models.CharField(max_length=30, verbose_name='Region')),
                ('Race', models.CharField(max_length=20, verbose_name='Race')),
                ('Avatar', models.ImageField(null=True, upload_to='img_url', verbose_name='Avatar')),
                ('Bio', models.TextField(default='', verbose_name='Bio')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
