# Generated by Django 4.1.1 on 2022-12-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='PId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='PId'),
        ),
    ]
