# Generated by Django 4.1.1 on 2022-12-24 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "Gid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="GId"
                    ),
                ),
                ("GName", models.CharField(max_length=30, verbose_name="GName")),
                ("BornTime", models.DateTimeField(auto_now=True, verbose_name="Time")),
                (
                    "Owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "Group",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "MId",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="MId"
                    ),
                ),
                (
                    "Type",
                    models.IntegerField(
                        choices=[(0, "个人"), (1, "群组")], verbose_name="Type"
                    ),
                ),
                ("ContextText", models.TextField(verbose_name="ContextText")),
                (
                    "Picture",
                    models.ImageField(
                        null=True, upload_to="img_url", verbose_name="Picture"
                    ),
                ),
                ("Time", models.DateTimeField(auto_now=True, verbose_name="Time")),
                (
                    "SendFrom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SendFrom",
                        to="backend.useraccount",
                    ),
                ),
                (
                    "SendToGroup",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.group",
                    ),
                ),
                (
                    "SendToPerson",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="SendToPerson",
                        to="backend.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "Message",
            },
        ),
        migrations.CreateModel(
            name="OperatorGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isOwner",
                    models.IntegerField(
                        choices=[(0, "不是"), (1, "是")], verbose_name="isOwner"
                    ),
                ),
                (
                    "CodeName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.useraccount",
                    ),
                ),
                (
                    "Gid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="backend.group"
                    ),
                ),
            ],
            options={
                "db_table": "operator_group",
                "unique_together": {("Gid", "CodeName")},
            },
        ),
    ]
