# Generated by Django 4.1.1 on 2022-11-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_account_approve_queue_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="account_approve_queue",
            new_name="AccountApproveQueue",
        ),
        migrations.RenameModel(
            old_name="user_account",
            new_name="UserAccount",
        ),
        migrations.RenameModel(
            old_name="user_profile",
            new_name="UserProfile",
        ),
    ]
