# Generated by Django 4.1.1 on 2022-12-11 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_passage_pid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passage',
            options={'ordering': ['PId']},
        ),
    ]
