# Generated by Django 4.1.1 on 2022-12-24 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_group_message_operatorgroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "RId",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="RId"
                    ),
                ),
                ("Content", models.TextField(verbose_name="Content")),
                (
                    "AttachedNId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.passage",
                    ),
                ),
                (
                    "Replier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="backend.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "Reply",
            },
        ),
    ]
