# Generated by Django 4.1.1 on 2022-12-11 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_passage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='LastEditTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='LastEditTime'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='PostDate',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='PostDate'),
        ),
    ]
