# Generated by Django 4.1.1 on 2022-11-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_rename_account_approve_queue_accountapprovequeue_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="Permission",
            field=models.PositiveSmallIntegerField(verbose_name="Permission"),
        ),
    ]
