# Generated by Django 4.1.1 on 2022-11-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_alter_accountapprovequeue_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="Avatar",
        ),
        migrations.AlterField(
            model_name="accountapprovequeue",
            name="Description",
            field=models.TextField(default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="accountapprovequeue",
            name="Permission",
            field=models.IntegerField(default=3, verbose_name="Permission"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="Mail",
            field=models.CharField(default="", max_length=20, verbose_name="Mail"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Bio",
            field=models.TextField(default="", verbose_name="Bio"),
        ),
    ]
