# Generated by Django 4.1.1 on 2022-11-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_remove_userprofile_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="Avatar",
            field=models.ImageField(
                null=True, upload_to="img_url", verbose_name="Avatar"
            ),
        ),
    ]
